In [1]:
"""
Librerias a utilizar
"""
import matplotlib.pyplot as plt
import pandas as pd
from datetime import datetime
import numpy as np
import math
import csv
from scipy import stats

10

,id_paciente,sexo,nacimiento,edad_2016,centro,sector,fecha_diagnostico,edad_diagnostico,anos_con_DM,severity_index,comorbidity_index
0,17458,F,1951-08-09,65,MTC,AZUL,2004-12-14,53,12,0,2
1,32777,F,1963-03-07,53,JPII,AZUL,2010-05-14,47,6,2,1
2,8203,F,1976-06-20,40,MTC,VERDE,2016-05-02,40,0,0,1
3,16397,F,1944-08-20,72,MTC,AZUL,2004-10-05,60,12,2,2
4,16399,M,1947-11-22,69,MTC,AZUL,2004-11-25,57,12,0,1
5,114704,F,1940-08-11,76,SAH,VERDE,2013-10-01,73,3,0,0
6,114706,F,1929-05-06,87,SAH,AZUL,2013-10-01,84,3,2,1
7,40979,M,1952-11-12,64,JPII,AZUL,2006-12-27,54,10,4,2
8,46425,F,1942-09-17,74,SAH,AZUL,2008-05-23,66,8,5,2
9,73752,F,1944-09-29,72,SAH,AZUL,2014-02-17,70,2,2,2
10,65561,F,1947-07-24,69,MTC,AZUL,2007-07-30,60,9,0,1
11,106522,M,1952-02-18,64,JPII,AZUL,2011-12-26,59,5,5,1
12,49181,F,1986-09-11,30,SAH,VERDE,2016-07-27,30,0,0,0
13,65569,F,1938-01-02,78,SAH,AZUL,2008-01-21,70,8,3,0
14,17755,M,1943-03-04,73,MTC,AZUL,2012-04-18,69,4,2,3
15,57382,M,1976-02-28,40,JPII,VERDE,2009-06-30,33,7,0,0
16,24615,F,1956-12-21,60,MTC,AZUL,2005-09-09,49,11,0,2
17,41004,M,1983-07-12,33,JPII,AZUL,2011-04-05,28,5,0,1
18,98351,F,1938-10-20,78,SAH,AZUL,2010-04-26,72,6,1,0
19,57394,F,1961-12-11,55,JPII,VERDE,2015-02-17,54,1,0,1
20,16435,F,1952-02-24,64,MTC,VERDE,2006-03-09,54,10,1,3
21,73781,F,1963-07-30,53,SAH,VERDE,2008-11-24,45,8,1,3
22,90171,F,1943-09-29,73,SAH,VERDE,2009-06-05,66,7,2,2
23,49214,F,1974-12-16,42,SAH,VERDE,2011-11-22,37,5,0,0
24,8255,F,1947-06-26,69,MTC,VERDE,2004-05-05,57,12,2,2
25,32834,M,1964-12-26,52,JPII,VERDE,2014-12-03,50,2,0,2
26,40971,F,1945-11-07,71,JPII,AZUL,2007-03-05,62,9,0,2
27,32836,F,1973-09-03,43,JPII,VERDE,2014-04-25,41,2,0,1
28,8261,M,1947-07-03,69,MTC,VERDE,2004-09-27,57,12,1,4
29,57415,F,1947-04-13,69,MTC,AZUL,2007-11-23,60,9,1,1
...,...,...,...,...,...,...,...,...,...,...,...
3339,114620,M,1933-08-09,83,JPII,VERDE,2013-09-12,80,3,0,0
3340,46410,F,1978-06-15,38,SAH,VERDE,2015-03-17,37,1,0,2
3341,114624,F,1941-10-11,75,MTC,AZUL,2013-10-03,72,3,0,1
3342,24514,F,1966-09-20,50,MTC,AZUL,2005-12-13,39,11,0,2
3343,16323,M,1963-09-27,53,SAH,VERDE,2012-07-04,49,4,1,0
3344,4086,F,1939-04-29,77,MTC,AZUL,2005-01-07,66,11,2,3
3345,49099,F,1957-11-23,59,JPII,AZUL,2006-05-10,49,10,1,4
3346,73677,F,1954-10-08,62,SAH,AZUL,2007-11-02,53,9,8,3
3347,24527,M,1943-11-17,73,MTC,AZUL,1999-07-20,56,17,3,1
3348,40913,M,1972-06-08,44,JPII,VERDE,2011-04-07,39,5,0,1
3349,57298,M,1963-07-10,53,SAH,VERDE,2007-10-09,44,9,0,2
3350,8147,F,1967-11-01,49,MTC,VERDE,2012-01-27,45,4,0,1
3351,106456,F,2011-11-03,5,JPII,VERDE,2014-05-30,3,2,0,0
3352,90073,M,1963-12-10,53,SAH,VERDE,2009-09-02,46,7,0,0
3353,42319,F,1958-10-17,58,JPII,VERDE,2014-12-17,56,2,0,3
3354,117413,M,1941-01-15,75,SAH,VERDE,2014-06-04,73,2,2,0
3355,81888,F,1946-12-30,70,JPII,VERDE,2008-05-15,62,8,3,1
3356,24549,M,1939-04-30,77,MTC,VERDE,2005-08-19,66,11,4,2
3357,65510,M,1949-10-25,67,JPII,VERDE,2015-01-05,66,1,0,0
3358,90090,M,1960-10-12,56,MTC,VERDE,2015-09-28,55,1,0,0
3359,81900,F,1955-01-29,61,JPII,VERDE,2015-04-30,60,1,0,1
3360,35461,F,1953-10-28,63,JPII,AZUL,2014-02-10,61,2,0,3
3361,64376,M,1947-12-20,69,SAH,VERDE,2012-01-26,65,4,0,1
3362,83115,M,1950-07-29,66,SAH,VERDE,2008-07-07,58,8,0,2
3363,40644,F,1965-09-21,51,JPII,AZUL,2005-01-24,40,11,0,3
3364,24566,M,1970-05-25,46,MTC,VERDE,2012-04-10,42,4,0,0
3365,114679,F,1927-04-01,89,SAH,AZUL,2013-09-05,86,3,0,2
3366,65532,M,1964-07-10,52,SAH,VERDE,2014-11-24,50,2,0,0
3367,8190,F,1935-04-29,81,MTC,VERDE,2008-05-05,73,8,2,1
3368,42325,M,1956-07-10,60,SAH,VERDE,2007-12-12,51,9,1,2

In [2]:
"""
Paths
"""

hba1c = "hba1c_3369.csv"

"""
Listas y diccionarios

"""
patients_list = []
cluster_patient = {}
list_transition = []

In [3]:


def filter_patients(patients_list):

    """
    Lee el archivo de ruta en chosen_patients y toma la columna 'id_paciente',
    crea una lista con los id's de los pacientes y los agrega en el caso de que no
    esten en la lista patients_list 

    """
    
    data = pd.read_csv(hba1c, sep=';')
    for patient in zip(data['id_paciente']):
        if patient not in patients_list:
            patients_list.append(patient)
            


filter_patients(patients_list)
#Lista con los pacientes que se han hecho el Examen hba1c
patients_list = [x[0] for x in patients_list]

In [4]:
"""
Programa

"""

# Leemos ambos archivos
data_hba1c = pd.read_csv(hba1c, sep=';')
data_hba1c['fecha'] = pd.to_datetime(data_hba1c['fecha'], infer_datetime_format=True)

list_hba1c = [list(x) for x in zip(data_hba1c["id_paciente"],data_hba1c["fecha"], data_hba1c["examen_hba1c"] )]

[110, Timestamp('2014-05-03 00:00:00'), 6.0999999999999996]

In [14]:

def obtener_examenes_pacientes(min_measure, lista_id_pacientes, list_hba1c):
        
    # diccionario que tiene como llave el id del paciente y 
    #como valor los resultados la transicion y los examenes ordenados segun fecha
    resultados = {}
    # recorro todos los pacientes
    for id_paciente in lista_id_pacientes:
        # lista con los examenes del paciente
        filtro_hba1c_id = list(filter(lambda x: x[0] == id_paciente , list_hba1c))
        # si el paciente tiene una sola medicion, no se considera 
        if len(filtro_hba1c_id) > min_measure:
            # recorre cada una de las transiciones 
            resultados[id_paciente] = sorted(filtro_hba1c_id, key = lambda x: x[1])        
        else:
            pass
    return resultados

dic = obtener_examenes_pacientes(1, patients_list, list_hba1c)

In [15]:
print(dic[110])

[[110, Timestamp('2014-05-03 00:00:00'), 6.0999999999999996], [110, Timestamp('2014-10-10 00:00:00'), 11.199999999999999], [110, Timestamp('2015-05-06 00:00:00'), 5.9000000000000004], [110, Timestamp('2015-08-01 00:00:00'), 6.5999999999999996]]

In [24]:

def hba1c_label(hba1c):
    if hba1c < 7:
        return "Normal"
    elif 7 <= hba1c < 9:
        return "Moderately-High"
    elif 9 <= hba1c < 10.5:
        return "High"
    else:
        return "Very-High"

def hba1c_category(hba1c):
    if hba1c < 7:
        return 1
    elif 7 <= hba1c <= 9:
        return 2
    elif hba1c > 9:
        return 3

def calcular_datos(measure, patients_list, list_hba1c):
        
    patient_curves = {}
    # {id:[Examenes...], id:[Examenes...], ....}
    patient_hba1c = obtener_examenes_pacientes(measure, patients_list, list_hba1c)
    id_pacientes = list(patient_hba1c.keys())
    transiciones = {}
    for patient in patient_hba1c:
            # resultados ordenados por fecha
            resultados = [x[2] for x in patient_hba1c[patient]]
            # fechas de los resultados
            fechas = [x[1] for x in patient_hba1c[patient]]
            
            if len(resultados) > measure:    
                
                diferencia_de_fechas = []
                fecha_inicio = fechas[0]
                for i in range(len(fechas)):
                    diferencia_de_fechas.append(int(str(fechas[i]-fecha_inicio).split(" ")[0]))
                first_hba1c = resultados[0]
                last_hba1c = resultados[-1]
                max_hba1c = max(resultados)
                min_hba1c = min(resultados)
                avg_hba1c = round(np.average(resultados), 2)
                std_hba1c = round(np.std(resultados), 2)
                measurements = len(resultados)
                slopes = []
                deltas_up = []
                deltas_down = []
                days_up_ptge = 0
                transitions = str(hba1c_category(resultados[0]))
                days = diferencia_de_fechas[-1]
                bad_measurements = 0
                good_measurements = 0
                mediate_measurements = 0
                
                # clasificamos resultados de examenes entre buenos, intermedios y malos segun hba1c
                for i in range(len(resultados)):
                    if resultados[i] > 9:
                        bad_measurements += 1
                    elif 7 <= resultados[i] <= 9:
                        mediate_measurements += 1
                    else:
                        good_measurements += 1             
                # calculos los slope
                
                for i in range(len(resultados)-1):

                    if resultados[i+1] < 7 and resultados[i] < 7:
                        delta_y = 0
                    else:
                        delta_y = resultados[i+1] - resultados[i]

                    delta_x = int(str(fechas[i+1] - fechas[i]).split(" ")[0])

                    slope = delta_y/delta_x
                    slopes.append(slope)

                    if delta_y >= 0:
                        deltas_up.append(delta_y)
                        days_up_ptge += delta_x
                    else:
                        deltas_down.append(delta_y)

                    if hba1c_category(resultados[i+1]) != hba1c_category(resultados[i]):
                        transitions += str(hba1c_category(resultados[i+1]))

                max_label = hba1c_label(max_hba1c)
                min_label = hba1c_label(min_hba1c)
                first_label = hba1c_label(first_hba1c)
                last_label = hba1c_label(last_hba1c)
                avg_hba1c_label = hba1c_label(avg_hba1c)
                avg_slope_days = round(np.average(slopes), 5)
                avg_slope_months = round(avg_slope_days*180, 5)
                max_slope = round(max(slopes)*180, 2)
                min_slope = round(min(slopes)*180, 2)
                delta_hba1c_up = round(sum(deltas_up), 2)
                delta_hba1c_down = round(sum(deltas_down), 2)
                delta_hba1c = round(last_hba1c-first_hba1c, 2)
                range_hba1c = round(max_hba1c-min_hba1c, 2)

                days_up_ptge = round((days_up_ptge*100)/int(str(fechas[-1] - fechas[0]).split(" ")[0]), 1)
                if len(deltas_up) == 0:
                    max_delta_up = 0
                else:
                    max_delta_up = round(max(deltas_up), 2)

                slope, intercept, r_value, p_value, std_err = stats.linregress(diferencia_de_fechas, resultados)

                if max_hba1c < 7 or (avg_hba1c < 7 and (mediate_measurements == 1 and bad_measurements == 0)):
                    category = 'Compensado'

                elif slope < 0 and last_hba1c < 7:
                    category = 'Mejora'

                elif max_hba1c <= 9:  
                    category = 'Medianamente Descompensado'

                else:
                    category = 'Altamente Descompensado'

                if not patient in patient_curves:

                    patient_curves[patient] = [patient, first_hba1c, first_label, 
                                                last_hba1c, last_label, max_hba1c, max_label, min_hba1c, 
                                                min_label, avg_slope_days, avg_slope_months, avg_hba1c, 
                                                std_hba1c, avg_hba1c_label, measurements, max_slope, 
                                                min_slope, delta_hba1c_up,delta_hba1c_down, max_delta_up, 
                                                days_up_ptge, delta_hba1c, range_hba1c, category, slope, days]
            else:
                pass
            
    return patient_curves

In [26]:

def write_file(min_measurement, delimiter, patients_list, list_hba1c):
    count = 0
    rows = calcular_datos(min_measurement, patients_list, list_hba1c)
    report = open('Camilo.csv', 'w', newline='')
    wr = csv.writer(report, delimiter=delimiter)
    header = ['id_paciente','primera', 'primera_cat', 'ultima', 'ultima_cat', 'max', 'max_cat', 'min', 'min_cat',
              'pendiente_dias_avg', 'pendiente_mes_avg', 'hba1c_promedio', 'hba1c_std', 'hba1c_promedio_cat',
              'mediciones', 'max_pend', 'min_pend', 'aumento_hba1c', 'caida_hba1c', 'max_aumento_hba1c', 'ptje_aumento',
              'delta_hba1c', 'rango', 'cluster', 'pend_reg', 'total_dias']
    wr.writerow(header)
    for patient in rows:
        wr.writerow(rows[patient])
        count += 1
    print('Pacientes reporte: ', count)
    report.close()

    
write_file(1, ";", patients_list, list_hba1c)

Pacientes reporte:  2962